version: "3.8"

services:
  app:
    build: .
    container_name: express_app
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_NAME=express_db
      - DB_PORT=5432
    volumes:
      - .:/app
      - /app/node_modules
  db:
    image: "docker.io/bitnami/postgresql:15"
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: express_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
